tweak layout for the story page
Ismael-KG/A-History-of-Research-Ethics pull request #46
Opened 2021-12-14 21:08 UTC by yochannah

### Related issue

n/a

### Proposed change

layout tweakery

### Reviewers

- [ ] Reviewers selected

I think this isn't quite right yet but on track?

2021-12-14 21:09 UTC, yochannah commented
<img width="806" alt="layout showing story image to the right and basic info to the fleft, followed by the stroy" src="https://user-images.githubusercontent.com/9271438/146079649-e66aefa4-2506-4893-8582-15c6da80bcd8.png">

2021-12-14 21:36 UTC, yochannah commented
this is what happens if wip is true: 
<img width="772" alt="shows story with an notification that it is a work in progress" src="https://user-images.githubusercontent.com/9271438/146083026-266c398a-4a91-466b-9f0a-2feccfa69167.png">

2021-12-15 08:24 UTC, Ismael-KG commented
@yochannah, can you make it so WIPs just show a title, a photo, a year, and a message like:

> **This story is still a work in progress.** If you would like to help write it or know some useful resources that should be referenced, please share some thoughts in the following GitHub issue! [LINK]

2021-12-15 19:41 UTC, Ismael-KG requested changes

2021-12-15 19:41 UTC, Ismael-KG commented on _layouts/story.html
> +    This is a work in progress and may need additional edits to meet the protocols.
**This story is still a work in progress.** If you would like to help write it or know some useful resources that should be referenced, please share some thoughts in the following GitHub issue!

2021-12-17 10:23 UTC, Ismael-KG approved these changes
I am not sure what I am approving.

2021-12-17 17:48 UTC, yochannah commented
okay this is wip conditions now: 
![shows the wording suggested by ismael](https://user-images.githubusercontent.com/9271438/146586681-95b07dd7-069c-47b6-9a05-858ae5a596c1.png)

2021-12-17 17:50 UTC, yochannah commented
I added a title because otherwise what are we even updating? 
![image showing th title added to the WIP text](https://user-images.githubusercontent.com/9271438/146586840-6f207931-589c-44b3-b3ad-513a1a25a0e3.png)

2021-12-17 18:58 UTC, merged